// Concrete, drawable nouns. Order matters: seeded games index into this list,
// so append new words at the end to keep old challenge links stable.
export const WORDS: readonly string[] = [
  // animals
  "cat", "dog", "fish", "bird", "horse", "cow", "pig", "sheep", "goat", "duck",
  "chicken", "rabbit", "mouse", "snake", "frog", "turtle", "lion", "tiger", "bear", "elephant",
  "giraffe", "zebra", "monkey", "whale", "shark", "octopus", "crab", "snail", "spider", "bee",
  "butterfly", "ant", "owl", "penguin", "fox", "wolf", "deer", "camel", "kangaroo", "koala",
  "panda", "dolphin", "jellyfish", "starfish", "bat", "worm", "ladybug", "dragon", "unicorn", "dinosaur",
  "squirrel", "hedgehog", "parrot", "flamingo", "swan", "eagle", "seal", "crocodile", "lobster", "peacock",
  "llama", "hippo", "rhino", "beaver", "raccoon", "skunk", "moose", "sloth", "bunny", "caterpillar",
  "dragonfly", "mosquito", "scorpion", "seahorse", "squid", "shrimp", "goldfish", "chick", "rooster", "turkey",
  // food
  "apple", "banana", "cherry", "grapes", "lemon", "orange", "pear", "pineapple", "strawberry", "watermelon",
  "carrot", "potato", "tomato", "corn", "mushroom", "onion", "pepper", "broccoli", "bread", "cheese",
  "egg", "pizza", "burger", "sandwich", "cake", "cookie", "donut", "candy", "lollipop", "ice cream",
  "popcorn", "pretzel", "taco", "sushi", "cupcake", "pie", "honey", "milk", "coffee", "teapot",
  "avocado", "coconut", "peanut", "soup", "steak", "bacon", "sausage", "hot dog", "waffle", "pancake",
  "croissant", "peach", "kiwi", "garlic", "pumpkin", "eggplant", "cucumber", "popsicle", "noodles", "fries",
  "chocolate", "lemonade", "baguette", "chili", "olive", "lettuce", "cereal", "toast", "jam", "butter",
  // household objects
  "chair", "table", "bed", "lamp", "door", "window", "key", "lock", "clock", "watch",
  "phone", "computer", "laptop", "television", "camera", "radio", "guitar", "piano", "drum", "trumpet",
  "violin", "book", "pencil", "pen", "scissors", "ruler", "paintbrush", "envelope", "stamp", "box",
  "bag", "backpack", "suitcase", "umbrella", "glasses", "hat", "crown", "shoe", "boot", "sock",
  "shirt", "dress", "pants", "glove", "scarf", "tie", "belt", "ring", "necklace", "button",
  "zipper", "cup", "mug", "bottle", "plate", "bowl", "fork", "spoon", "knife", "frying pan",
  "pot", "kettle", "toaster", "fridge", "oven", "sink", "bathtub", "toilet", "toothbrush", "comb",
  "mirror", "towel", "soap", "candle", "lightbulb", "battery", "plug", "magnet", "hammer", "saw",
  "screwdriver", "wrench", "nail", "ladder", "shovel", "bucket", "broom", "rope", "chain", "anchor",
  "flag", "balloon", "kite", "ball", "dice", "puzzle", "robot", "rocket", "sword", "shield",
  "arrow", "trophy", "medal", "gift", "map", "globe", "compass", "telescope", "microscope", "headphones",
  "microphone", "calculator", "keyboard", "remote", "fan", "vase", "pillow", "blanket", "sofa", "shelf",
  "basket", "cage", "tent", "wallet", "coin", "diamond", "crayon", "paperclip", "stapler", "eraser",
  "notebook", "calendar", "newspaper", "picture frame", "bell", "whistle", "harp", "saxophone", "flute", "skateboard",
  "teddy bear", "doll", "yo-yo", "wheelchair", "stroller", "spatula", "whisk", "rolling pin", "jar", "can",
  "trash can", "mailbox", "padlock", "hourglass", "sunglasses", "lipstick", "perfume", "hairdryer", "iron", "sewing machine",
  // transport
  "bicycle", "scooter", "helmet", "ski", "surfboard", "sailboat", "boat", "ship", "submarine", "canoe",
  "car", "bus", "truck", "train", "tractor", "taxi", "ambulance", "fire truck", "helicopter", "airplane",
  "motorcycle", "wheel", "parachute", "hot air balloon", "van", "traffic light", "rollercoaster", "tank", "spaceship", "satellite",
  // nature & weather
  "sun", "moon", "star", "cloud", "rain", "snowflake", "lightning", "rainbow", "tornado", "volcano",
  "mountain", "island", "river", "wave", "beach", "cactus", "tree", "flower", "rose", "tulip",
  "sunflower", "leaf", "bush", "palm tree", "rock", "fire", "planet", "comet", "feather", "seashell",
  "nest", "spider web", "bone", "skull", "acorn", "pinecone", "clover", "puddle", "iceberg", "waterfall",
  // places & buildings
  "house", "castle", "tower", "bridge", "igloo", "lighthouse", "windmill", "barn", "pyramid", "fence",
  "chimney", "fountain", "swing", "windsock", "treehouse", "skyscraper", "church", "stadium", "well", "dog house",
  // body
  "eye", "nose", "mouth", "ear", "hand", "foot", "finger", "tooth", "heart", "brain",
  "leg", "lips", "mustache", "beard", "skeleton", "muscle", "footprint", "fingerprint", "thumbs up", "wink",
  // characters
  "ghost", "alien", "pirate", "ninja", "wizard", "witch", "king", "queen", "snowman", "mermaid",
  "angel", "vampire", "zombie", "clown", "astronaut", "cowboy", "baby", "superhero", "princess", "knight",
  // misc
  "bomb", "axe", "mask", "magic wand", "cauldron", "potion", "treasure chest", "ticket", "ufo", "lantern",
  "campfire", "fireworks", "birthday cake", "present", "snow globe", "hammock", "sandcastle", "scarecrow", "trampoline", "maze",
];

// Accepted alternatives. Matching one of these counts as "close", not exact.
export const ALIASES: Readonly<Record<string, readonly string[]>> = {
  cat: ["kitty", "kitten"],
  dog: ["puppy", "doggy"],
  rabbit: ["bunny", "hare"],
  bunny: ["rabbit"],
  mouse: ["rat"],
  snake: ["serpent"],
  hippo: ["hippopotamus"],
  rhino: ["rhinoceros"],
  crocodile: ["alligator", "croc"],
  dinosaur: ["dino", "trex"],
  chick: ["chicken", "bird"],
  rooster: ["chicken", "cock"],
  ladybug: ["ladybird", "beetle", "bug"],
  burger: ["hamburger", "cheeseburger"],
  donut: ["doughnut"],
  fries: ["chips", "french fries"],
  grapes: ["grape"],
  "ice cream": ["cone", "gelato"],
  popsicle: ["ice lolly", "icecream"],
  "hot dog": ["sausage"],
  teapot: ["kettle"],
  kettle: ["teapot"],
  phone: ["telephone", "cellphone", "smartphone", "mobile"],
  television: ["tv", "telly"],
  laptop: ["computer"],
  computer: ["pc", "monitor", "laptop"],
  fridge: ["refrigerator"],
  sofa: ["couch"],
  glasses: ["spectacles"],
  sunglasses: ["glasses", "shades"],
  gift: ["present"],
  present: ["gift"],
  mug: ["cup"],
  cup: ["mug", "glass"],
  trophy: ["cup"],
  bag: ["purse", "handbag"],
  backpack: ["bag", "rucksack"],
  pants: ["trousers", "jeans"],
  boot: ["shoe"],
  shoe: ["boot", "sneaker"],
  lightbulb: ["bulb", "light", "idea"],
  "frying pan": ["pan", "skillet"],
  paintbrush: ["brush"],
  remote: ["controller"],
  "trash can": ["bin", "garbage can", "dustbin"],
  bicycle: ["bike", "cycle"],
  motorcycle: ["motorbike", "bike"],
  airplane: ["plane", "jet", "aeroplane"],
  helicopter: ["chopper"],
  boat: ["ship", "sailboat"],
  ship: ["boat"],
  sailboat: ["boat", "yacht"],
  ufo: ["spaceship", "flying saucer"],
  spaceship: ["rocket", "ufo"],
  rocket: ["spaceship"],
  "fire truck": ["fire engine"],
  taxi: ["cab", "car"],
  sun: ["sunshine"],
  star: ["starfish"],
  cloud: ["clouds"],
  rain: ["raincloud"],
  snowflake: ["snow"],
  lightning: ["bolt", "thunder"],
  tornado: ["twister", "hurricane"],
  seashell: ["shell"],
  rock: ["stone", "boulder"],
  "palm tree": ["palm", "tree"],
  house: ["home", "hut"],
  "dog house": ["kennel"],
  heart: ["love"],
  mustache: ["moustache"],
  "thumbs up": ["thumb", "like"],
  "treasure chest": ["treasure", "chest"],
  "magic wand": ["wand"],
  "birthday cake": ["cake"],
  campfire: ["fire", "bonfire"],
  fireworks: ["firework"],
  "teddy bear": ["teddy", "bear"],
  "spider web": ["web", "cobweb"],
  "picture frame": ["frame", "painting", "picture"],
  superhero: ["hero"],
  knight: ["armor", "armour"],
  ghost: ["spirit"],
  alien: ["martian"],
  skull: ["head"],
  hairdryer: ["hair dryer", "blow dryer"],
};
